--
-- PostgreSQL database dump
--

\restrict fzh8pael3R5Ye0OdhHSWh1wG15wCydxznK4cOfjl6hw0AFCP8Jg7WMPXnajsgO1

-- Dumped from database version 17.9
-- Dumped by pg_dump version 17.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: module_master; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.module_master (module_id, org_id, module_name, module_code, module_description, module_route, module_icon, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at) OVERRIDING SYSTEM VALUE VALUES (1, 1, 'Dashboard', 'DASHBOARD', 'Dashboard Module', '/dashboard', 'dashboard', 1, true, 1, '2026-06-22 11:55:50.150273', NULL, NULL, NULL, NULL);
INSERT INTO public.module_master (module_id, org_id, module_name, module_code, module_description, module_route, module_icon, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at) OVERRIDING SYSTEM VALUE VALUES (2, 1, 'Agents', 'AGENTS', 'Agent Management', '/agents', 'server', 2, true, 1, '2026-06-22 11:55:50.150273', NULL, NULL, NULL, NULL);
INSERT INTO public.module_master (module_id, org_id, module_name, module_code, module_description, module_route, module_icon, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at) OVERRIDING SYSTEM VALUE VALUES (3, 1, 'Databases', 'DATABASES', 'Database Monitoring', '/databases', 'database', 3, true, 1, '2026-06-22 11:55:50.150273', NULL, NULL, NULL, NULL);
INSERT INTO public.module_master (module_id, org_id, module_name, module_code, module_description, module_route, module_icon, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at) OVERRIDING SYSTEM VALUE VALUES (4, 1, 'Cloud', 'CLOUD', 'Cloud Monitoring', '/cloud', 'cloud', 4, true, 1, '2026-06-22 11:55:50.150273', NULL, NULL, NULL, NULL);
INSERT INTO public.module_master (module_id, org_id, module_name, module_code, module_description, module_route, module_icon, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at) OVERRIDING SYSTEM VALUE VALUES (5, 1, 'Infrastructure', 'INFRASTRUCTURE', 'Infrastructure Monitoring', '/infra', 'desktop', 5, true, 1, '2026-06-22 11:55:50.150273', NULL, NULL, NULL, NULL);
INSERT INTO public.module_master (module_id, org_id, module_name, module_code, module_description, module_route, module_icon, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at) OVERRIDING SYSTEM VALUE VALUES (6, 1, 'ML / AI', 'ML_AI', 'Machine Learning & AI', '/ml', 'brain', 6, true, 1, '2026-06-22 11:55:50.150273', NULL, NULL, NULL, NULL);
INSERT INTO public.module_master (module_id, org_id, module_name, module_code, module_description, module_route, module_icon, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at) OVERRIDING SYSTEM VALUE VALUES (7, 1, 'Alerts', 'ALERTS', 'Alert Management', '/alerts', 'alert', 7, true, 1, '2026-06-22 11:55:50.150273', NULL, NULL, NULL, NULL);
INSERT INTO public.module_master (module_id, org_id, module_name, module_code, module_description, module_route, module_icon, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at) OVERRIDING SYSTEM VALUE VALUES (8, 1, 'Administration', 'ADMINISTRATION', 'Administration', '/administration', 'shield', 8, true, 1, '2026-06-22 11:55:50.150273', NULL, NULL, NULL, NULL);
INSERT INTO public.module_master (module_id, org_id, module_name, module_code, module_description, module_route, module_icon, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at) OVERRIDING SYSTEM VALUE VALUES (9, 1, 'Settings', 'SETTINGS', 'Application Settings', '/settings', 'settings', 9, true, 1, '2026-06-22 11:55:50.150273', NULL, NULL, NULL, NULL);
INSERT INTO public.module_master (module_id, org_id, module_name, module_code, module_description, module_route, module_icon, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at) OVERRIDING SYSTEM VALUE VALUES (10, 1, 'ChatBot', 'CHATBOT', 'AI ChatBot', '/chatbot', 'chat', 10, true, 1, '2026-06-22 11:55:50.150273', NULL, NULL, NULL, NULL);
INSERT INTO public.module_master (module_id, org_id, module_name, module_code, module_description, module_route, module_icon, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at) OVERRIDING SYSTEM VALUE VALUES (11, 1, '__TMPMOD__', '__TMP__', NULL, NULL, NULL, 99, false, 1, '2026-06-22 16:03:51.890043', NULL, NULL, 1, '2026-06-22 16:03:51.890043');
INSERT INTO public.module_master (module_id, org_id, module_name, module_code, module_description, module_route, module_icon, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at) OVERRIDING SYSTEM VALUE VALUES (13, 1, 'Logs', 'LOGS', NULL, '/logs', 'logs', 12, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL);


--
-- Data for Name: page_master; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (1, 'Connections', '/connections', NULL, 'database', 1, true, 1, '2026-06-22 12:07:25.955032', NULL, NULL, NULL, NULL, 1, 3, 0, 'CONNECTIONS', 'Database Connections', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (2, 'Database Servers', '/databases', NULL, 'server', 2, true, 1, '2026-06-22 12:07:25.955032', NULL, NULL, NULL, NULL, 1, 3, 0, 'DATABASE_SERVERS', 'Database Servers', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (9, 'Add Connection', '/connections/add', NULL, 'add', 1, true, 1, '2026-06-22 12:08:04.732101', NULL, NULL, NULL, NULL, 1, 3, 1, 'ADD_CONNECTION', 'Add Database Connection', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (10, 'Add Database Server', '/databases/add-server', NULL, 'add', 1, true, 1, '2026-06-22 12:08:13.039433', NULL, NULL, NULL, NULL, 1, 3, 2, 'ADD_DATABASE_SERVER', 'Add Database Server', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (11, 'Add OS Server', '/databases/add-os-server', NULL, 'desktop', 2, true, 1, '2026-06-22 12:08:13.039433', NULL, NULL, NULL, NULL, 1, 3, 2, 'ADD_OS_SERVER', 'Add Operating System Server', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (12, 'Server Detail', '/connections/server/:serverId', NULL, 'server', 3, true, 1, '2026-06-22 12:08:13.039433', NULL, NULL, NULL, NULL, 1, 3, 2, 'SERVER_DETAIL', 'Database Server Detail', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (13, 'Dashboard', '/mysql-dashboard/:id', NULL, 'dashboard', 1, true, 1, '2026-06-22 12:08:43.658133', NULL, NULL, NULL, NULL, 1, 3, 3, 'MYSQL_DASHBOARD', 'MySQL Dashboard', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (14, 'Slow Queries', '/mysql-dashboard/:id/slow-queries', NULL, 'clock', 2, true, 1, '2026-06-22 12:08:43.658133', NULL, NULL, NULL, NULL, 1, 3, 3, 'MYSQL_SLOW_QUERIES', 'MySQL Slow Queries', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (15, 'Error Logs', '/mysql-dashboard/:id/error-logs', NULL, 'error', 3, true, 1, '2026-06-22 12:08:43.658133', NULL, NULL, NULL, NULL, 1, 3, 3, 'MYSQL_ERROR_LOGS', 'MySQL Error Logs', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (16, 'Error Analysis', '/mysql-dashboard/:id/error-analysis', NULL, 'analytics', 4, true, 1, '2026-06-22 12:08:43.658133', NULL, NULL, NULL, NULL, 1, 3, 3, 'MYSQL_ERROR_ANALYSIS', 'MySQL Error Analysis', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (17, 'Self Heal', '/mysql-dashboard/:id/self-heal', NULL, 'repair', 5, true, 1, '2026-06-22 12:08:43.658133', NULL, NULL, NULL, NULL, 1, 3, 3, 'MYSQL_SELF_HEAL', 'MySQL Self Heal', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (18, 'Index Analysis', '/mysql-dashboard/:id/index-analysis', NULL, 'search', 6, true, 1, '2026-06-22 12:08:43.658133', NULL, NULL, NULL, NULL, 1, 3, 3, 'MYSQL_INDEX_ANALYSIS', 'MySQL Index Analysis', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (19, 'Backup', '/mysql-dashboard/:id/backup', NULL, 'backup', 7, true, 1, '2026-06-22 12:08:43.658133', NULL, NULL, NULL, NULL, 1, 3, 3, 'MYSQL_BACKUP', 'MySQL Backup', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (20, 'Reports', '/mysql-dashboard/:id/reports', NULL, 'report', 8, true, 1, '2026-06-22 12:08:43.658133', NULL, NULL, NULL, NULL, 1, 3, 3, 'MYSQL_REPORTS', 'MySQL Reports', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (21, 'Dashboard', '/postgresql-dashboard/:id', NULL, 'dashboard', 1, true, 1, '2026-06-22 12:09:06.258757', NULL, NULL, NULL, NULL, 1, 3, 4, 'POSTGRESQL_DASHBOARD', 'PostgreSQL Dashboard', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (22, 'Slow Queries', '/postgresql-dashboard/:id/slow-queries', NULL, 'clock', 2, true, 1, '2026-06-22 12:09:06.258757', NULL, NULL, NULL, NULL, 1, 3, 4, 'POSTGRESQL_SLOW_QUERIES', 'PostgreSQL Slow Queries', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (23, 'Query Detail', '/postgresql-dashboard/:id/slow-queries/detail', NULL, 'search', 3, true, 1, '2026-06-22 12:09:06.258757', NULL, NULL, NULL, NULL, 1, 3, 4, 'POSTGRESQL_QUERY_DETAIL', 'PostgreSQL Query Detail', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (24, 'Error Logs', '/postgresql-dashboard/:id/error-logs', NULL, 'error', 4, true, 1, '2026-06-22 12:09:06.258757', NULL, NULL, NULL, NULL, 1, 3, 4, 'POSTGRESQL_ERROR_LOGS', 'PostgreSQL Error Logs', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (25, 'Index Analysis', '/postgresql-dashboard/:id/index-analysis', NULL, 'analytics', 5, true, 1, '2026-06-22 12:09:06.258757', NULL, NULL, NULL, NULL, 1, 3, 4, 'POSTGRESQL_INDEX_ANALYSIS', 'PostgreSQL Index Analysis', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (26, 'Backup', '/postgresql-dashboard/:id/backup', NULL, 'backup', 6, true, 1, '2026-06-22 12:09:06.258757', NULL, NULL, NULL, NULL, 1, 3, 4, 'POSTGRESQL_BACKUP', 'PostgreSQL Backup', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (27, 'Reports', '/postgresql-dashboard/:id/reports', NULL, 'report', 7, true, 1, '2026-06-22 12:09:06.258757', NULL, NULL, NULL, NULL, 1, 3, 4, 'POSTGRESQL_REPORTS', 'PostgreSQL Reports', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (28, 'Dashboard', '/oracle-dashboard/:id', NULL, 'dashboard', 1, true, 1, '2026-06-22 12:09:25.904042', NULL, NULL, NULL, NULL, 1, 3, 5, 'ORACLE_DASHBOARD', 'Oracle Dashboard', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (29, 'Slow Queries', '/oracle-dashboard/:id/slow-queries', NULL, 'clock', 2, true, 1, '2026-06-22 12:09:25.904042', NULL, NULL, NULL, NULL, 1, 3, 5, 'ORACLE_SLOW_QUERIES', 'Oracle Slow Queries', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (30, 'Error Logs', '/oracle-dashboard/:id/error-logs', NULL, 'error', 3, true, 1, '2026-06-22 12:09:25.904042', NULL, NULL, NULL, NULL, 1, 3, 5, 'ORACLE_ERROR_LOGS', 'Oracle Error Logs', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (31, 'Index Analysis', '/oracle-dashboard/:id/index-analysis', NULL, 'analytics', 4, true, 1, '2026-06-22 12:09:25.904042', NULL, NULL, NULL, NULL, 1, 3, 5, 'ORACLE_INDEX_ANALYSIS', 'Oracle Index Analysis', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (32, 'Reports', '/oracle-dashboard/:id/reports', NULL, 'report', 5, true, 1, '2026-06-22 12:09:25.904042', NULL, NULL, NULL, NULL, 1, 3, 5, 'ORACLE_REPORTS', 'Oracle Reports', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (33, 'Live Queries', '/oracle-dashboard/:id/live-queries', NULL, 'activity', 6, true, 1, '2026-06-22 12:09:25.904042', NULL, NULL, NULL, NULL, 1, 3, 5, 'ORACLE_LIVE_QUERIES', 'Oracle Live Queries', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (34, 'Dashboard', '/mssql-dashboard/:id', NULL, 'dashboard', 1, true, 1, '2026-06-22 12:09:47.001743', NULL, NULL, NULL, NULL, 1, 3, 6, 'MSSQL_DASHBOARD', 'Microsoft SQL Server Dashboard', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (35, 'Slow Queries', '/mssql-dashboard/:id/slow-queries', NULL, 'clock', 2, true, 1, '2026-06-22 12:09:47.001743', NULL, NULL, NULL, NULL, 1, 3, 6, 'MSSQL_SLOW_QUERIES', 'Microsoft SQL Server Slow Queries', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (36, 'Error Logs', '/mssql-dashboard/:id/error-logs', NULL, 'error', 3, true, 1, '2026-06-22 12:09:47.001743', NULL, NULL, NULL, NULL, 1, 3, 6, 'MSSQL_ERROR_LOGS', 'Microsoft SQL Server Error Logs', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (37, 'Index Analysis', '/mssql-dashboard/:id/index-analysis', NULL, 'analytics', 4, true, 1, '2026-06-22 12:09:47.001743', NULL, NULL, NULL, NULL, 1, 3, 6, 'MSSQL_INDEX_ANALYSIS', 'Microsoft SQL Server Index Analysis', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (38, 'Backup', '/mssql-dashboard/:id/backup', NULL, 'backup', 5, true, 1, '2026-06-22 12:09:47.001743', NULL, NULL, NULL, NULL, 1, 3, 6, 'MSSQL_BACKUP', 'Microsoft SQL Server Backup', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (39, 'Dashboard', '/mongodb-dashboard/:id', NULL, 'dashboard', 1, true, 1, '2026-06-22 12:10:11.28762', NULL, NULL, NULL, NULL, 1, 3, 7, 'MONGODB_DASHBOARD', 'MongoDB Dashboard', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (40, 'Slow Operations', '/mongodb-dashboard/:id/slow-operations', NULL, 'clock', 2, true, 1, '2026-06-22 12:10:11.28762', NULL, NULL, NULL, NULL, 1, 3, 7, 'MONGODB_SLOW_OPERATIONS', 'MongoDB Slow Operations', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (41, 'Error Logs', '/mongodb-dashboard/:id/error-logs', NULL, 'error', 3, true, 1, '2026-06-22 12:10:11.28762', NULL, NULL, NULL, NULL, 1, 3, 7, 'MONGODB_ERROR_LOGS', 'MongoDB Error Logs', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (42, 'Collection Analysis', '/mongodb-dashboard/:id/collection-analysis', NULL, 'analytics', 4, true, 1, '2026-06-22 12:10:11.28762', NULL, NULL, NULL, NULL, 1, 3, 7, 'MONGODB_COLLECTION_ANALYSIS', 'MongoDB Collection Analysis', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (43, 'Backup', '/mongodb-dashboard/:id/backup', NULL, 'backup', 5, true, 1, '2026-06-22 12:10:11.28762', NULL, NULL, NULL, NULL, 1, 3, 7, 'MONGODB_BACKUP', 'MongoDB Backup', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (44, 'Dashboard', '/clickhouse-dashboard/:id', NULL, 'dashboard', 1, true, 1, '2026-06-22 12:10:35.591502', NULL, NULL, NULL, NULL, 1, 3, 8, 'CLICKHOUSE_DASHBOARD', 'ClickHouse Dashboard', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (45, 'Slow Queries', '/clickhouse-dashboard/:id/slow-queries', NULL, 'clock', 2, true, 1, '2026-06-22 12:10:35.591502', NULL, NULL, NULL, NULL, 1, 3, 8, 'CLICKHOUSE_SLOW_QUERIES', 'ClickHouse Slow Queries', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (46, 'Error Logs', '/clickhouse-dashboard/:id/error-logs', NULL, 'error', 3, true, 1, '2026-06-22 12:10:35.591502', NULL, NULL, NULL, NULL, 1, 3, 8, 'CLICKHOUSE_ERROR_LOGS', 'ClickHouse Error Logs', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (47, 'Table Analysis', '/clickhouse-dashboard/:id/table-analysis', NULL, 'analytics', 4, true, 1, '2026-06-22 12:10:35.591502', NULL, NULL, NULL, NULL, 1, 3, 8, 'CLICKHOUSE_TABLE_ANALYSIS', 'ClickHouse Table Analysis', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (48, 'Administration', NULL, NULL, 'shield', 1, true, 1, '2026-06-22 12:11:13.445678', NULL, NULL, NULL, NULL, 1, 8, 0, 'ADMINISTRATION', 'Administration Module', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (49, 'Organizations', '/organizations', NULL, 'organization', 1, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'ORGANIZATION_MASTER', 'Organization Management', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (50, 'Departments', '/departments', NULL, 'building', 2, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'DEPARTMENT_MASTER', 'Department Management', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (51, 'Designations', '/designations', NULL, 'briefcase', 3, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'DESIGNATION_MASTER', 'Designation Management', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (52, 'Employees', '/employees', NULL, 'people', 4, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'EMPLOYEE_MASTER', 'Employee Management', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (53, 'Users', '/users', NULL, 'person', 5, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'USER_MASTER', 'User Management', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (54, 'Roles', '/roles', NULL, 'shield', 6, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'ROLE_MASTER', 'Role Management', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (55, 'Modules', '/modules', NULL, 'grid', 7, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'MODULE_MASTER', 'Module Management', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (56, 'Pages', '/pages', NULL, 'document', 8, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'PAGE_MASTER', 'Page Management', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (57, 'Permissions', '/permissions', NULL, 'lock', 9, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'PERMISSION_MASTER', 'Permission Management', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (58, 'Role Permissions', '/role-permissions', NULL, 'key', 10, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'ROLE_PERMISSION', 'Role Permission Mapping', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (59, 'Audit Logs', '/audit-logs', NULL, 'history', 11, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'AUDIT_LOG', 'Audit Logs', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (60, 'Login History', '/login-history', NULL, 'clock', 12, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'LOGIN_HISTORY', 'Login History', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (61, 'Password History', '/password-history', NULL, 'password', 13, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'PASSWORD_HISTORY', 'Password History', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (62, 'User Sessions', '/user-sessions', NULL, 'desktop', 14, true, 1, '2026-06-22 12:11:19.295998', NULL, NULL, NULL, NULL, 1, 8, 48, 'USER_SESSION', 'User Sessions', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (63, 'ChatBot', NULL, NULL, 'chat', 1, true, 1, '2026-06-22 12:12:28.586757', NULL, NULL, NULL, NULL, 1, 10, 0, 'CHATBOT', 'AI ChatBot Module', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (64, 'AI ChatBot', '/chatbot', NULL, 'chat', 1, true, 1, '2026-06-22 12:12:35.681234', NULL, NULL, NULL, NULL, 1, 10, 63, 'AI_CHATBOT', 'AI Database Assistant', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (65, 'Chat History', '/chatbot/history', NULL, 'history', 2, true, 1, '2026-06-22 12:12:35.681234', NULL, NULL, NULL, NULL, 1, 10, 63, 'CHAT_HISTORY', 'Chat Conversation History', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (66, 'AI Configuration', '/chatbot/configuration', NULL, 'settings', 3, true, 1, '2026-06-22 12:12:35.681234', NULL, NULL, NULL, NULL, 1, 10, 63, 'AI_CONFIGURATION', 'AI Model Configuration', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (3, 'MySQL', '/mysql-servers', NULL, 'mysql', 3, true, 1, '2026-06-22 12:07:25.955032', 1, '2026-06-22 13:05:58.481515', NULL, NULL, 1, 3, 0, 'MYSQL', 'MySQL Monitoring', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (4, 'PostgreSQL', '/postgresql-servers', NULL, 'postgresql', 4, true, 1, '2026-06-22 12:07:25.955032', 1, '2026-06-22 13:05:58.481515', NULL, NULL, 1, 3, 0, 'POSTGRESQL', 'PostgreSQL Monitoring', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (5, 'Oracle', '/oracle-servers', NULL, 'oracle', 5, true, 1, '2026-06-22 12:07:25.955032', 1, '2026-06-22 13:05:58.481515', NULL, NULL, 1, 3, 0, 'ORACLE', 'Oracle Monitoring', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (6, 'SQL Server', '/mssql-servers', NULL, 'mssql', 6, true, 1, '2026-06-22 12:07:25.955032', 1, '2026-06-22 13:05:58.481515', NULL, NULL, 1, 3, 0, 'MSSQL', 'Microsoft SQL Server', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (7, 'MongoDB', '/mongodb-servers', NULL, 'mongodb', 7, true, 1, '2026-06-22 12:07:25.955032', 1, '2026-06-22 13:05:58.481515', NULL, NULL, 1, 3, 0, 'MONGODB', 'MongoDB Monitoring', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (8, 'ClickHouse', '/clickhouse-servers', NULL, 'clickhouse', 8, true, 1, '2026-06-22 12:07:25.955032', 1, '2026-06-22 13:05:58.481515', NULL, NULL, 1, 3, 0, 'CLICKHOUSE', 'ClickHouse Monitoring', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (67, 'Dashboard', '/dashboard', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 1, 0, 'DASHBOARD', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (68, 'Agents', '/agents', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 2, 0, 'AGENTS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (69, 'Agent Detail', '/agents/:id', NULL, NULL, 2, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 2, 68, 'AGENT_DETAIL', NULL, false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (70, 'Cloud', '/cloud', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 4, 0, 'CLOUD', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (71, 'Infrastructure', '/infra', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 5, 0, 'INFRASTRUCTURE', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (72, 'ML / AI', '/ml', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 6, 0, 'ML_AI', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (73, 'Alerts', '/alerts', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 7, 0, 'ALERTS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (74, 'Settings', '/settings', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 9, 0, 'SETTINGS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (75, 'Performance', '/mysql-dashboard/:id/performance', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 13, 'MYSQL_TAB_PERFORMANCE', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (76, 'Queries', '/mysql-dashboard/:id/queries', NULL, NULL, 2, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 13, 'MYSQL_TAB_QUERIES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (77, 'Databases', '/mysql-dashboard/:id/databases', NULL, NULL, 3, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 13, 'MYSQL_TAB_DATABASES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (78, 'Tables', '/mysql-dashboard/:id/tables', NULL, NULL, 4, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 13, 'MYSQL_TAB_TABLES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (79, 'Locks', '/mysql-dashboard/:id/locks', NULL, NULL, 5, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 13, 'MYSQL_TAB_LOCKS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (80, 'Replication', '/mysql-dashboard/:id/replication', NULL, NULL, 6, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 13, 'MYSQL_TAB_REPLICATION', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (81, 'Users', '/mysql-dashboard/:id/users', NULL, NULL, 7, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 13, 'MYSQL_TAB_USERS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (82, 'Storage', '/mysql-dashboard/:id/storage', NULL, NULL, 8, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 13, 'MYSQL_TAB_STORAGE', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (83, 'Logs', '/mysql-dashboard/:id/logs', NULL, NULL, 9, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 13, 'MYSQL_TAB_LOGS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (84, 'Performance', '/postgresql-dashboard/:id/performance', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 21, 'POSTGRESQL_TAB_PERFORMANCE', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (85, 'Queries', '/postgresql-dashboard/:id/queries', NULL, NULL, 2, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 21, 'POSTGRESQL_TAB_QUERIES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (86, 'Databases', '/postgresql-dashboard/:id/databases', NULL, NULL, 3, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 21, 'POSTGRESQL_TAB_DATABASES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (87, 'Tables', '/postgresql-dashboard/:id/tables', NULL, NULL, 4, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 21, 'POSTGRESQL_TAB_TABLES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (88, 'Locks', '/postgresql-dashboard/:id/locks', NULL, NULL, 5, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 21, 'POSTGRESQL_TAB_LOCKS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (89, 'Replication', '/postgresql-dashboard/:id/replication', NULL, NULL, 6, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 21, 'POSTGRESQL_TAB_REPLICATION', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (90, 'Users', '/postgresql-dashboard/:id/users', NULL, NULL, 7, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 21, 'POSTGRESQL_TAB_USERS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (91, 'Storage', '/postgresql-dashboard/:id/storage', NULL, NULL, 8, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 21, 'POSTGRESQL_TAB_STORAGE', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (92, 'Config', '/postgresql-dashboard/:id/config', NULL, NULL, 9, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 21, 'POSTGRESQL_TAB_CONFIG', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (93, 'Performance', '/oracle-dashboard/:id/performance', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_PERFORMANCE', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (94, 'Sessions', '/oracle-dashboard/:id/sessions', NULL, NULL, 2, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_SESSIONS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (95, 'SQL', '/oracle-dashboard/:id/sql', NULL, NULL, 3, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_SQL', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (96, 'Tablespaces', '/oracle-dashboard/:id/tablespaces', NULL, NULL, 4, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_TABLESPACES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (97, 'Objects', '/oracle-dashboard/:id/objects', NULL, NULL, 5, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_OBJECTS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (98, 'Tables', '/oracle-dashboard/:id/schemabrowser', NULL, NULL, 6, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_SCHEMABROWSER', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (99, 'Data Guard', '/oracle-dashboard/:id/dataguard', NULL, NULL, 7, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_DATAGUARD', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (100, 'Redo Logs', '/oracle-dashboard/:id/redologs', NULL, NULL, 8, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_REDOLOGS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (101, 'Processes', '/oracle-dashboard/:id/processes', NULL, NULL, 9, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_PROCESSES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (102, 'Users', '/oracle-dashboard/:id/users', NULL, NULL, 10, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_USERS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (103, 'Sys Stats', '/oracle-dashboard/:id/systemstats', NULL, NULL, 11, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_SYSTEMSTATS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (104, 'Slow Queries', '/oracle-dashboard/:id/slowqueries', NULL, NULL, 12, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_SLOWQUERIES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (105, 'Locks', '/oracle-dashboard/:id/locks', NULL, NULL, 13, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_LOCKS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (106, 'Parameters', '/oracle-dashboard/:id/parameters', NULL, NULL, 14, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 28, 'ORACLE_TAB_PARAMETERS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (107, 'Performance', '/mssql-dashboard/:id/performance', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 34, 'MSSQL_TAB_PERFORMANCE', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (108, 'Queries', '/mssql-dashboard/:id/queries', NULL, NULL, 2, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 34, 'MSSQL_TAB_QUERIES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (109, 'Databases', '/mssql-dashboard/:id/databases', NULL, NULL, 3, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 34, 'MSSQL_TAB_DATABASES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (110, 'Tables', '/mssql-dashboard/:id/tables', NULL, NULL, 4, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 34, 'MSSQL_TAB_TABLES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (111, 'Locks', '/mssql-dashboard/:id/locks', NULL, NULL, 5, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 34, 'MSSQL_TAB_LOCKS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (112, 'Replication', '/mssql-dashboard/:id/replication', NULL, NULL, 6, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 34, 'MSSQL_TAB_REPLICATION', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (113, 'Users', '/mssql-dashboard/:id/users', NULL, NULL, 7, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 34, 'MSSQL_TAB_USERS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (114, 'Storage', '/mssql-dashboard/:id/storage', NULL, NULL, 8, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 34, 'MSSQL_TAB_STORAGE', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (115, 'Operations', '/mongodb-dashboard/:id/operations', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 39, 'MONGODB_TAB_OPERATIONS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (116, 'Profiler', '/mongodb-dashboard/:id/profiler', NULL, NULL, 2, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 39, 'MONGODB_TAB_PROFILER', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (117, 'Collections', '/mongodb-dashboard/:id/collections', NULL, NULL, 3, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 39, 'MONGODB_TAB_COLLECTIONS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (118, 'Indexes', '/mongodb-dashboard/:id/indexes', NULL, NULL, 4, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 39, 'MONGODB_TAB_INDEXES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (119, 'Replication', '/mongodb-dashboard/:id/replication', NULL, NULL, 5, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 39, 'MONGODB_TAB_REPLICATION', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (120, 'Oplog', '/mongodb-dashboard/:id/oplog', NULL, NULL, 6, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 39, 'MONGODB_TAB_OPLOG', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (121, 'Sharding', '/mongodb-dashboard/:id/sharding', NULL, NULL, 7, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 39, 'MONGODB_TAB_SHARDING', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (122, 'Transactions', '/mongodb-dashboard/:id/transactions', NULL, NULL, 8, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 39, 'MONGODB_TAB_TRANSACTIONS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (123, 'WiredTiger', '/mongodb-dashboard/:id/wiredtiger', NULL, NULL, 9, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 39, 'MONGODB_TAB_WIREDTIGER', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (124, 'Users', '/mongodb-dashboard/:id/users', NULL, NULL, 10, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 39, 'MONGODB_TAB_USERS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (125, 'Slow Queries', '/mongodb-dashboard/:id/slowqueries', NULL, NULL, 11, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 39, 'MONGODB_TAB_SLOWQUERIES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (126, 'Error Logs', '/mongodb-dashboard/:id/errorlogs', NULL, NULL, 12, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 39, 'MONGODB_TAB_ERRORLOGS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (127, 'Queries', '/clickhouse-dashboard/:id/queries', NULL, NULL, 1, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 44, 'CLICKHOUSE_TAB_QUERIES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (128, 'Query Log', '/clickhouse-dashboard/:id/querylog', NULL, NULL, 2, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 44, 'CLICKHOUSE_TAB_QUERYLOG', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (129, 'Tables', '/clickhouse-dashboard/:id/tables', NULL, NULL, 3, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 44, 'CLICKHOUSE_TAB_TABLES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (130, 'Partitions', '/clickhouse-dashboard/:id/partitions', NULL, NULL, 4, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 44, 'CLICKHOUSE_TAB_PARTITIONS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (131, 'Merges', '/clickhouse-dashboard/:id/merges', NULL, NULL, 5, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 44, 'CLICKHOUSE_TAB_MERGES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (132, 'Replicas', '/clickhouse-dashboard/:id/replicas', NULL, NULL, 6, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 44, 'CLICKHOUSE_TAB_REPLICAS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (133, 'Clusters', '/clickhouse-dashboard/:id/clusters', NULL, NULL, 7, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 44, 'CLICKHOUSE_TAB_CLUSTERS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (134, 'Databases', '/clickhouse-dashboard/:id/databases', NULL, NULL, 8, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 44, 'CLICKHOUSE_TAB_DATABASES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (135, 'Settings', '/clickhouse-dashboard/:id/settings', NULL, NULL, 9, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 44, 'CLICKHOUSE_TAB_SETTINGS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (136, 'System Metrics', '/clickhouse-dashboard/:id/sysmetrics', NULL, NULL, 10, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 44, 'CLICKHOUSE_TAB_SYSMETRICS', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (137, 'Slow Queries', '/clickhouse-dashboard/:id/slowqueries', NULL, NULL, 11, true, 1, '2026-06-22 13:05:58.481515', NULL, NULL, NULL, NULL, 1, 3, 44, 'CLICKHOUSE_TAB_SLOWQUERIES', NULL, true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (138, 'Aws Dashboard', '/aws-cloud', NULL, '', 1, true, 1, '2026-06-22 16:36:22.156898', NULL, NULL, NULL, NULL, 1, 4, 0, 'AWS', 'cloud development', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (139, 'Reports', '/mssql-dashboard/:id/reports', NULL, 'report', 8, true, 1, '2026-06-29 17:04:14.471744', NULL, NULL, NULL, NULL, 1, 3, 6, 'MSSQL_REPORTS', 'SQL Server Reports', true);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (140, 'Cloud Accounts', '/cloud/accounts', NULL, 'cloud', 1, true, 1, '2026-06-30 11:52:08.172941', NULL, NULL, NULL, NULL, 1, 4, 70, 'CLOUD_ACCOUNTS', 'Cloud accounts (AWS/Azure/OCI)', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (141, 'Cloud Resources', '/cloud/resources', NULL, 'cloud', 2, true, 1, '2026-06-30 11:52:08.172941', NULL, NULL, NULL, NULL, 1, 4, 70, 'CLOUD_RESOURCES', 'Discovered cloud resources', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (142, 'Cloud Resource Detail', '/cloud/resources/:resourceId', NULL, 'cloud', 3, true, 1, '2026-06-30 11:52:08.172941', NULL, NULL, NULL, NULL, 1, 4, 70, 'CLOUD_RESOURCE_DETAIL', 'Single resource detail', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (143, 'Cloud Cost', '/cloud/cost', NULL, 'cloud', 4, true, 1, '2026-06-30 11:52:08.172941', NULL, NULL, NULL, NULL, 1, 4, 70, 'CLOUD_COST', 'Cloud cost analysis', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (144, 'Cloud Security', '/cloud/security', NULL, 'cloud', 5, true, 1, '2026-06-30 11:52:08.172941', NULL, NULL, NULL, NULL, 1, 4, 70, 'CLOUD_SECURITY', 'Cloud security posture', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (145, 'Cloud Topology', '/cloud/topology', NULL, 'cloud', 6, true, 1, '2026-06-30 11:52:08.172941', NULL, NULL, NULL, NULL, 1, 4, 70, 'CLOUD_TOPOLOGY', 'Cloud topology map', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (146, 'Cloud Compliance', '/cloud/compliance', NULL, 'cloud', 7, true, 1, '2026-06-30 11:52:08.172941', NULL, NULL, NULL, NULL, 1, 4, 70, 'CLOUD_COMPLIANCE', 'Cloud compliance', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (147, 'Cloud Alerts', '/cloud/alerts', NULL, 'cloud', 8, true, 1, '2026-06-30 11:52:08.172941', NULL, NULL, NULL, NULL, 1, 4, 70, 'CLOUD_ALERTS', 'Cloud alerts', false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (158, 'Deploy Agent', '/agents/deploy', NULL, NULL, 3, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL, 1, 2, 0, 'AGENTS_DEPLOY', NULL, false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (159, 'Add Data', '/agents/setup', NULL, NULL, 4, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL, 1, 2, 0, 'AGENTS_SETUP', NULL, false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (160, 'Agent DB Setup', '/agents/setup/:tech', NULL, NULL, 5, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL, 1, 2, 0, 'AGENTS_SETUP_TECH', NULL, false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (161, 'Add Website', '/agents/setup/website', NULL, NULL, 6, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL, 1, 2, 0, 'AGENTS_SETUP_WEBSITE', NULL, false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (162, 'Agent Sessions', '/agents/:id/sessions', NULL, NULL, 7, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL, 1, 2, 0, 'AGENTS_ID_SESSIONS', NULL, false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (163, 'Add Data (Databases)', '/databases/add-data', NULL, NULL, 15, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL, 1, 3, 0, 'DATABASES_ADD_DATA', NULL, false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (164, 'Database Setup', '/databases/setup/:tech', NULL, NULL, 16, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL, 1, 3, 0, 'DATABASES_SETUP_TECH', NULL, false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (165, 'Host Detail', '/infra/:id', NULL, NULL, 2, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL, 1, 5, 0, 'INFRA_ID', NULL, false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (166, 'File Explorer', '/infra/:id/files', NULL, NULL, 3, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL, 1, 5, 0, 'INFRA_ID_FILES', NULL, false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (167, 'Administration Home', '/administration', NULL, NULL, 15, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL, 1, 8, 0, 'ADMINISTRATION_1', NULL, false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (168, 'Organization Detail', '/administration/:orgId', NULL, NULL, 16, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL, 1, 8, 0, 'ADMINISTRATION_ORGID', NULL, false);
INSERT INTO public.page_master (page_id, page_name, page_url, mobile_url, icon_name, display_order, is_active, created_by, created_at, modified_by, modified_at, deleted_by, deleted_at, org_id, module_id, parent_id, page_code, page_description, is_menu) OVERRIDING SYSTEM VALUE VALUES (169, 'Logs', '/logs', NULL, NULL, 1, true, 1, '2026-07-07 04:29:31.336955', NULL, NULL, NULL, NULL, 1, 13, 0, 'LOGS', NULL, true);


--
-- Name: module_master_module_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.module_master_module_id_seq', 13, true);


--
-- Name: page_page_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.page_page_id_seq', 169, true);


--
-- PostgreSQL database dump complete
--

\unrestrict fzh8pael3R5Ye0OdhHSWh1wG15wCydxznK4cOfjl6hw0AFCP8Jg7WMPXnajsgO1

