-- RBAC page_master sync — aligns page_master with actual app routes
-- module_master: no changes (all 10 modules already present & correct)
-- Applied 2026-06-22. page_id is GENERATED ALWAYS AS IDENTITY (omitted on insert).
BEGIN;

-- 1) UPDATE: give DB-type parent rows their /{tech}-servers URL
UPDATE page_master SET page_url='/mysql-servers', modified_by=1, modified_at=now() WHERE page_id=3;
UPDATE page_master SET page_url='/postgresql-servers', modified_by=1, modified_at=now() WHERE page_id=4;
UPDATE page_master SET page_url='/oracle-servers', modified_by=1, modified_at=now() WHERE page_id=5;
UPDATE page_master SET page_url='/mssql-servers', modified_by=1, modified_at=now() WHERE page_id=6;
UPDATE page_master SET page_url='/mongodb-servers', modified_by=1, modified_at=now() WHERE page_id=7;
UPDATE page_master SET page_url='/clickhouse-servers', modified_by=1, modified_at=now() WHERE page_id=8;

-- 2) INSERT: module-landing pages (modules 1,2,4,5,6,7,9 had no pages)
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (1,0,'Dashboard','/dashboard','DASHBOARD',1,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (2,0,'Agents','/agents','AGENTS',1,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (2,(SELECT page_id FROM page_master WHERE page_code='AGENTS'),'Agent Detail','/agents/:id','AGENT_DETAIL',2,false,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (4,0,'Cloud','/cloud','CLOUD',1,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (5,0,'Infrastructure','/infra','INFRASTRUCTURE',1,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (6,0,'ML / AI','/ml','ML_AI',1,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (7,0,'Alerts','/alerts','ALERTS',1,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (9,0,'Settings','/settings','SETTINGS',1,true,true,1,1,now());

-- 3) INSERT: dashboard tabs (children of each Dashboard page)
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,13,'Performance','/mysql-dashboard/:id/performance','MYSQL_TAB_PERFORMANCE',1,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,13,'Queries','/mysql-dashboard/:id/queries','MYSQL_TAB_QUERIES',2,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,13,'Databases','/mysql-dashboard/:id/databases','MYSQL_TAB_DATABASES',3,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,13,'Tables','/mysql-dashboard/:id/tables','MYSQL_TAB_TABLES',4,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,13,'Locks','/mysql-dashboard/:id/locks','MYSQL_TAB_LOCKS',5,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,13,'Replication','/mysql-dashboard/:id/replication','MYSQL_TAB_REPLICATION',6,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,13,'Users','/mysql-dashboard/:id/users','MYSQL_TAB_USERS',7,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,13,'Storage','/mysql-dashboard/:id/storage','MYSQL_TAB_STORAGE',8,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,13,'Logs','/mysql-dashboard/:id/logs','MYSQL_TAB_LOGS',9,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,21,'Performance','/postgresql-dashboard/:id/performance','POSTGRESQL_TAB_PERFORMANCE',1,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,21,'Queries','/postgresql-dashboard/:id/queries','POSTGRESQL_TAB_QUERIES',2,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,21,'Databases','/postgresql-dashboard/:id/databases','POSTGRESQL_TAB_DATABASES',3,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,21,'Tables','/postgresql-dashboard/:id/tables','POSTGRESQL_TAB_TABLES',4,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,21,'Locks','/postgresql-dashboard/:id/locks','POSTGRESQL_TAB_LOCKS',5,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,21,'Replication','/postgresql-dashboard/:id/replication','POSTGRESQL_TAB_REPLICATION',6,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,21,'Users','/postgresql-dashboard/:id/users','POSTGRESQL_TAB_USERS',7,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,21,'Storage','/postgresql-dashboard/:id/storage','POSTGRESQL_TAB_STORAGE',8,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,21,'Config','/postgresql-dashboard/:id/config','POSTGRESQL_TAB_CONFIG',9,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Performance','/oracle-dashboard/:id/performance','ORACLE_TAB_PERFORMANCE',1,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Sessions','/oracle-dashboard/:id/sessions','ORACLE_TAB_SESSIONS',2,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'SQL','/oracle-dashboard/:id/sql','ORACLE_TAB_SQL',3,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Tablespaces','/oracle-dashboard/:id/tablespaces','ORACLE_TAB_TABLESPACES',4,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Objects','/oracle-dashboard/:id/objects','ORACLE_TAB_OBJECTS',5,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Tables','/oracle-dashboard/:id/schemabrowser','ORACLE_TAB_SCHEMABROWSER',6,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Data Guard','/oracle-dashboard/:id/dataguard','ORACLE_TAB_DATAGUARD',7,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Redo Logs','/oracle-dashboard/:id/redologs','ORACLE_TAB_REDOLOGS',8,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Processes','/oracle-dashboard/:id/processes','ORACLE_TAB_PROCESSES',9,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Users','/oracle-dashboard/:id/users','ORACLE_TAB_USERS',10,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Sys Stats','/oracle-dashboard/:id/systemstats','ORACLE_TAB_SYSTEMSTATS',11,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Slow Queries','/oracle-dashboard/:id/slowqueries','ORACLE_TAB_SLOWQUERIES',12,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Locks','/oracle-dashboard/:id/locks','ORACLE_TAB_LOCKS',13,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,28,'Parameters','/oracle-dashboard/:id/parameters','ORACLE_TAB_PARAMETERS',14,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,34,'Performance','/mssql-dashboard/:id/performance','MSSQL_TAB_PERFORMANCE',1,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,34,'Queries','/mssql-dashboard/:id/queries','MSSQL_TAB_QUERIES',2,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,34,'Databases','/mssql-dashboard/:id/databases','MSSQL_TAB_DATABASES',3,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,34,'Tables','/mssql-dashboard/:id/tables','MSSQL_TAB_TABLES',4,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,34,'Locks','/mssql-dashboard/:id/locks','MSSQL_TAB_LOCKS',5,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,34,'Replication','/mssql-dashboard/:id/replication','MSSQL_TAB_REPLICATION',6,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,34,'Users','/mssql-dashboard/:id/users','MSSQL_TAB_USERS',7,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,34,'Storage','/mssql-dashboard/:id/storage','MSSQL_TAB_STORAGE',8,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,39,'Operations','/mongodb-dashboard/:id/operations','MONGODB_TAB_OPERATIONS',1,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,39,'Profiler','/mongodb-dashboard/:id/profiler','MONGODB_TAB_PROFILER',2,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,39,'Collections','/mongodb-dashboard/:id/collections','MONGODB_TAB_COLLECTIONS',3,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,39,'Indexes','/mongodb-dashboard/:id/indexes','MONGODB_TAB_INDEXES',4,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,39,'Replication','/mongodb-dashboard/:id/replication','MONGODB_TAB_REPLICATION',5,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,39,'Oplog','/mongodb-dashboard/:id/oplog','MONGODB_TAB_OPLOG',6,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,39,'Sharding','/mongodb-dashboard/:id/sharding','MONGODB_TAB_SHARDING',7,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,39,'Transactions','/mongodb-dashboard/:id/transactions','MONGODB_TAB_TRANSACTIONS',8,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,39,'WiredTiger','/mongodb-dashboard/:id/wiredtiger','MONGODB_TAB_WIREDTIGER',9,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,39,'Users','/mongodb-dashboard/:id/users','MONGODB_TAB_USERS',10,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,39,'Slow Queries','/mongodb-dashboard/:id/slowqueries','MONGODB_TAB_SLOWQUERIES',11,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,39,'Error Logs','/mongodb-dashboard/:id/errorlogs','MONGODB_TAB_ERRORLOGS',12,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,44,'Queries','/clickhouse-dashboard/:id/queries','CLICKHOUSE_TAB_QUERIES',1,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,44,'Query Log','/clickhouse-dashboard/:id/querylog','CLICKHOUSE_TAB_QUERYLOG',2,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,44,'Tables','/clickhouse-dashboard/:id/tables','CLICKHOUSE_TAB_TABLES',3,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,44,'Partitions','/clickhouse-dashboard/:id/partitions','CLICKHOUSE_TAB_PARTITIONS',4,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,44,'Merges','/clickhouse-dashboard/:id/merges','CLICKHOUSE_TAB_MERGES',5,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,44,'Replicas','/clickhouse-dashboard/:id/replicas','CLICKHOUSE_TAB_REPLICAS',6,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,44,'Clusters','/clickhouse-dashboard/:id/clusters','CLICKHOUSE_TAB_CLUSTERS',7,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,44,'Databases','/clickhouse-dashboard/:id/databases','CLICKHOUSE_TAB_DATABASES',8,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,44,'Settings','/clickhouse-dashboard/:id/settings','CLICKHOUSE_TAB_SETTINGS',9,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,44,'System Metrics','/clickhouse-dashboard/:id/sysmetrics','CLICKHOUSE_TAB_SYSMETRICS',10,true,true,1,1,now());
INSERT INTO page_master (module_id,parent_id,page_name,page_url,page_code,display_order,is_menu,is_active,org_id,created_by,created_at) VALUES (3,44,'Slow Queries','/clickhouse-dashboard/:id/slowqueries','CLICKHOUSE_TAB_SLOWQUERIES',11,true,true,1,1,now());

COMMIT;
